### ISSUE TITLE
can't run huntlabs/hunt-skeleton

### ISSUE THREAD

**Issue by TaniukO** [huntlabs/hunt-extra#1]
hunt 1.6.1: target for configuration "library" is up to date.
hunt-extra 1.0.0: building configuration "library"...
../../../../.dub/packages/hunt-extra-1.0.0/hunt-extra/source/hunt/concurrency/Executors.d(402,12): Error: interface hunt.util.Common.Callable(V) at ../../../../.dub/packages/hunt-extra-1.0.0/hunt-extra/source/hunt/util/Common.d(110,1) conflicts with struct core.thread.context.Callable at /usr/include/dmd/druntime/import/core/thread/context.d(26,1)
/usr/bin/dmd failed with exit code 1.

may need to add the line 
"import hunt.util.Common:Callable;"
to hunt-extra-1.0.0/hunt-extra/source/hunt/concurrency/
FutureTask.d
and
Executors.d
?

**Comment by TaniukO** [comment]
it only on dmd 2.093
on dmd 2.0921 is no problem

**Comment by Heromyth** [comment]
Thanks. It's fixed in commit https://github.com/huntlabs/hunt-extra/commit/37a2e9cde7fe728f3181ea9e44da97577712b01d.
